### ISSUE TITLE
Enigmatic Legacy Forbidden Fruit Compatibility.

### ISSUE THREAD

**Issue by dmsw0303** [ElenaiDev/ElenaiDodge2.0#10]
The Forbidden Fruit in Enigmatic Legacy is an item that gives the player infinite hunger at the cost of health regeneration. When eating the fruit the hunger bar texture is replaced with a forbidden apple texture that's purple and doesn't decay. With Tough as Nails and Elenai Dodge installed, (which have thirst and feather bars implemented directly on top and below each other), Elenai dodge's feather bar disappears entirely, and Tough as Nails thirst bar will drop to occupy it's space. I initially thought this was an issue with Enigmatic Legacy but due to Tough as Nails' bar remaining present I assume this on ED's side.  At one point I thought maybe it was Enigmatic removing the bottom most bar, so I recreated all these steps with only Tough as Nails installed, yet its thirst bar was unphased. Leading me to believe this is most definitely Elenai Dodge

**Comment by ElenaiDev** [comment]
Hey!

So upon further testing, I have found that this also removes the GUI from mods such as Armor Toughness Bar. I'm looking into a workaround for this now :)

**Comment by ElenaiDev** [comment]
Closing as this was patched in 2.0.3!
