### ISSUE TITLE
[Suggestion] Second Config Option for Dodge While Airborne Feather Cost

### ISSUE THREAD

**Issue by dmsw0303** [ElenaiDev/ElenaiDodge2.0#11]
Currently with default settings (aside from having dodge while in air enabled) and a full "dodge" bar, you can dodge while in air like 10 times almost as if youre flying in survival. I love having this enabled because it feels like it makes vanilla movement a lot more rewarding and flexible. However, being able to basically float kind of kills immersion, I've tuned up these values, but I can't increase them by a lot without destroying the ability to dodge in most armors. I was wondering if you could add a second "feather cost" for dodging in air. Currently using 6 half feathers  for normal dodging, would love to use like 12 half feathers when you dodge in air. This balances it out a bit and allows both options to be present without killing immersion. While also allowing dodging in air to be an option specific to lighter armors. Thank you for your time and work!

**Comment by ElenaiDev** [comment]
Thank you for such a detailed feature request! I'll let you know when it's been added :)
