### ISSUE TITLE
[1.16.5] Dodge meter conflicts with Console Experience's Hovering Hotbar as of latest update

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [ElenaiDev/ElenaiDodge2.0#12]
Minecraft Version: 1.16.5
Forge Version: 36.0.42
Elenai Dodge Version: 2.0.3
Console Experience Version: 1.7.1

Hi,
When testing the most recent update to your mod (2.0.3) I noticed that when I'm playing in Survival mode the dodge meter conflicts with the hotbar. After some testing and narrowing down I discovered that this is a result of a feature from Console Experience called "Hovering Hotbar" which basically just moves the hotbar up a few pixels to make it look like it's floating.

This results in the hotbar conflicting with the dodge meter as seen here:
![2021-02-21_22 01 12](https://user-images.githubusercontent.com/64381954/108640570-672d4780-7492-11eb-814a-8927f5d147a9.png)
Disabling this feature from Console Experience does fix this, but this wasn't an issue in past versions of your mod and only seems to have started happening with this latest version (2.0.3). So I'm unsure why it has suddenly started conflicting now when this wasn't an issue in the past.

Here's my Latest Log: https://pastebin.com/82pvqsgR

Thanks for the awesome mod and keep up the great work!

Edit: This issue seems very similar to https://github.com/ElenaiDev/ElenaiDodge2.0/issues/5 Perhaps they're related or caused by the same thing?

Edit 2: Here's a link to Console Experience's page: https://www.curseforge.com/minecraft/mc-mods/console-hud

**Comment by Cixon** [comment]
**Bump!** 
I use this along with a mod called [Survival Overhaul](https://www.curseforge.com/minecraft/mc-mods/survival-overhaul) which works fine in-conjunction with Console Experience's GUI.

Only issue is proper GUI placement with Elenaidodge. Cheers!
https://i.imgur.com/Bkbv4QH.png

**Comment by ElenaiDev** [comment]
Thanks for the detailed description both of you! It's really helpful and allows me to quickly develop a new update.
Closed as this was patched in version 2.0.4.
