### ISSUE TITLE
[Suggestion] bring back double tap to dodge forward

### ISSUE THREAD

**Issue by erisdev** [ElenaiDev/ElenaiDodge2.0#13]
Just as it says in the title. The way it is now feels awkward to me, and I'd rather have the old behavior back. I'd be satisfied if it were a third mode or an additional boolean option or whatever.

There are mods that disable double tap to sprint for folks who are bothered by the overlap, but dodging forward into a sprint makes perfect sense to me.

**Comment by ElenaiDev** [comment]
Sure! Closed as this was added in version 2.0.4.

**Comment by erisdev** [comment]
Awesome, thank you!
