### ISSUE TITLE
The Betweenlands decay bar overlaps on the feather bar.

### ISSUE THREAD

**Issue by xelotex** [ElenaiDev/ElenaiDodge2.0#14]
(read the title) so you can't see how many dodges you have.

**Comment by ElenaiDev** [comment]
Hi! I'd love to help but would you be able to provide a little more information? I don't know much about the Betweenlands, so screenshots of the issue from the latest version of both mods would be super helpful :)

Thank you!
Elenai <3

**Comment by xelotex** [comment]
![2021-02-22_07 34 08](https://user-images.githubusercontent.com/70168682/108715401-71763280-74e0-11eb-9148-a8fea7cd8765.png)
 
has you can see, i can't see the feathers because of the decay bar of the betweenlands is superimposing to it, maybe if you put an option in the config that let us change the position of the feathers bar through the screen would help to fix this

**Comment by xelotex** [comment]
also: i'm playing with the latest version of your mod and with the version 3.7.1 of the betweenlands.

**Comment by ElenaiDev** [comment]
Thanks so much for your time!

I think that may be the best workaround, I'll see if I can automatically fix it but if not a manual override is always useful. Sorry for the inconvenience!
