### ISSUE TITLE
Dodge feather/stamina bar fills up while game is paused

### ISSUE THREAD

**Issue by SomeRandomPetey** [ElenaiDev/ElenaiDodge2.0#2]
Description: Your dodge feather meter will fill up if the game is paused in singleplayer, even though everything else in the world is paused.

Steps to reproduce:
1. Use some of your dodge feather meter
2. Pause the game in singleplayer
3. Watch the dodge meter fill

Expected result: dodge feather meter does not fill up while the game is paused
Actual result: meter fills up with the game paused

This is a bit op since in singleplayer you can just pause the game while fighting and wait for your dodge to recover.

**Comment by ElenaiDev** [comment]
Thanks so much for finding the issue!
I'll release a patch soon. Marking as closed as I have added this to my trello board.

Have a great day!

**Comment by meelock** [comment]
You probably want to mention the issue in the name of the commit that closes the issue, as it closes the issue automatically if you do.

**Comment by ElenaiDev** [comment]
Thank you, I'll do that in future!

This has now been fixed in Version 2.0.1.
