### ISSUE TITLE
feathers don't regenerate/ sometime regenerate when drinking a potion

### ISSUE THREAD

**Issue by Biviho** [ElenaiDev/ElenaiDodge2.0#21]
version: v1.0.8b for 1.12.2

tested on a chonky modpack (283 mods) and light modpack (23)

basically feathers don't regenerate or sometime regenerate after drinking a potion of feathery.
It's almost certain a problem with one of the mod in the chonky one, cause in the light one there are no problems.

i will try to find the culprit in the near future, but i can't say how much time it will take me.

**Comment by ElenaiDev** [comment]
Thank you! I can't do anything until the culprit mod is found, but I really appreciate you pointing out  the issue! :)

**Comment by Biviho** [comment]
Found it! by...total chance while testing other things (what a luck)

It looks like it's the Tan integration:

-without Tan everything work fine
-with Tan, feathers regenerate only if the last thirst drop on the left (the first that get consumed) is at least half full, if there is one missing full drop, then it stop regardless of the exaustion amount in the config for Tan integration

**Comment by ElenaiDev** [comment]
Hi again!

Closing as this is the intended functionality. I will be adding an option to decrease/disable the requirement at a later date, but the Config option you mention is actually how much thirst is **added** when the player regenerates a feather.

Hope this helps!
