### ISSUE TITLE
Crash with Classic Bar

### ISSUE THREAD

**Issue by Miner239** [ElenaiDev/ElenaiDodge2.0#26]
Hello, it's me again.

Crash on GUI render. https://paste.ee/p/cKewz

**Comment by ElenaiDev** [comment]
Oh dear. This is because I recently updated my API and it's broken the mod. I'll make a pull request to fix this shortly.

Thank you for reporting the issue!

**Comment by ElenaiDev** [comment]
Closing this as I've now sent a pull request fixing the issue. For now, just use Elenai Dodge 2 v1.0.8b to avoid the crash until Tfar uploads the update :)
