### ISSUE TITLE
[Suggestion] Ledge Grabbing

### ISSUE THREAD

**Issue by jarezzz** [ElenaiDev/ElenaiDodge2.0#27]
Ledge Grabbing can be enabled in the config, allowing you to boost up two block high ledges!

Why not? It was in a first version and it was awesome, no need for SmartMoving

**Comment by ElenaiDev** [comment]
I will be adding it in an addon for Elenai Dodge 2 titled 'Elenai Movement'.
Basically I'm trying to make the new versions names make sense and to make sure users know what they're downloading.

Elenai Movement will feature wall jumping and ledge grabbing just like Elenai Dodge 1, and hopefully some cool new optional additions too!

Have a great day and thank you for your patience!
Elenai <3

**Comment by ElenaiDev** [comment]
Also, thanks for saying it was awesome! The new version will hopefully be even better :)

**Comment by jarezzz** [comment]
Oh, cool, mate! Glad to hear that it will come back, also new feather system is great!
