### ISSUE TITLE
[Bug] Potions defaulting to feathery.

### ISSUE THREAD

**Issue by asakern1** [ElenaiDev/ElenaiDodge2.0#29]
I'm on the most recent 1.16 version and whenever I try to brew replenishment it turns into feathery, and when I try to add glowstone to forcefulness or endurance it turns into feathery 2. I have tried multiple times (in survival and creative) and it is not user error. Brewing feathery 1 and feathery 2 still works fine but the other potions are bugged.

**Comment by ElenaiDev** [comment]
Whoops! I don't know what I changed to cause the issue but it shouldn't be a problem to fix.

I'll keep you updated with the progress of the patch!

**Comment by ElenaiDev** [comment]
This is a very unusual issue. JEI is showing the recipes as correct, and my code is also logically completely correct.
Would you be able to tell me the exact version of forge you are operating? It would be really helpful.

**Comment by Jinman269** [comment]
I am having the same problem as well :(

**Comment by ElenaiDev** [comment]
Apologies this is taking so long!

I've been overwhelmed with other work the past month or two and am only now able to get back on track.
I've identified the issue and will release an update either this or next week rectifying it. 

Thank you so much for your patience!
Elenai <3
