### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Taknax** [ElenaiDev/ElenaiDodge2.0#3]
How i love useful nice mechanics. Great job.
I would wish a "dodge skill book", where its possible to higher the skilllevel and reduce cooldown.
Lovely work by ED2!

**Comment by ElenaiDev** [comment]
I really like this idea, although my aim for the coremod is to keep it simple.
I could always add integration to a mod such as reskillable? Where the user's agility level decreases dodge cooldown time.

**Comment by Taknax** [comment]
Brilliant. And i think too use a book to open the skill gui would make it feel totally survival. Lovely work! Maybe you can add 2 type of skills. Cooldownreduction and weight limit higher. You can joice per level. Which you want to increase. And you have to decide. Full cooldownreduction? Or full weight limit highring? Hybrid? 50-50? 75-25? So many ways with a simple tweak. :) Sorry for the suggestion rage. Was in the zone. xD

**Comment by Taknax** [comment]
O i missundertand. A modcompat to another mod is allways good. But you should make skillable as standalone too.

**Comment by ElenaiDev** [comment]
I'll close this as compatibility is on my to do list. I do really like your suggestion! I'm just trying to keep this mod very very simple. I'll release an API soon and then people will be able to make addons that do exactly what you're requesting. I hope you have a great day! :)

**Comment by Taknax** [comment]
Ty. I love your work. Go on!
