### ISSUE TITLE
[suggestion] adding elytra agility

### ISSUE THREAD

**Issue by Aarongrey13** [ElenaiDev/ElenaiDodge2.0#31]
the idea would be while using an elytra you have the ability to strafe left or right (possibly even doing a little spin animation ) and also add a special backwards strafe were you do a loopy loop in the air, causing you to end up a little bit further behind where you were.  essentially adding maneuvers to the elytra for more mobility at the cost of altitude and or Elena feathers.
-nately_jean_greywater ;P

**Comment by ElenaiDev** [comment]
Thank you for the suggestion!

This is now an upcoming mod I'll be working on in the future thanks to you (Elenai Elytra), so I'll close it as it's no longer relevant to Elenai Dodge 2.

Stay awesome!
Elenai <3
