### ISSUE TITLE
[Issue] Lang (en_US)?

### ISSUE THREAD

**Issue by Taknax** [ElenaiDev/ElenaiDodge2.0#32]
Thier is a little issue by the advancements. Maybe the en_US file not loadet?
https://i.imgur.com/1wb6MUy.png

**Comment by ElenaiDev** [comment]
Thank you for pointing this out!

I'll close this now as I've already patched it for the version coming out in the next week or so, and my proxy isn't letting me push to my GitHub repo at the moment.

Have an awesome day!
Elenai <3
