### ISSUE TITLE
PlayerEx support

### ISSUE THREAD

**Issue by lilmrmagoo** [ElenaiDev/ElenaiDodge2.0#37]
PlayerEx is a mod that adds a cool rpg style leveling system and expands upon the base attribute system in minecraft. It would be cool if elenai dodge had support for it where you might have a attribute that increase stamina and or reduces the amount of weight. The mod can be found here https://www.curseforge.com/minecraft/mc-mods/playerex?page=3#c81

**Comment by ElenaiDev** [comment]
Thanks for the suggestion!

I'd be happy to do this when the source code is released for the 1.16 version, however until then I am unfortunately unable to do anything.

I'll close this for now, but if you notice the 1.16.X source code become available let me know and I'll open it again!

Thank you for your understanding,
Elenai <3
