### ISSUE TITLE
Suggestion: Make Tough As Nails' Thirst mechanic dictate Feather regeneration.

### ISSUE THREAD

**Issue by ArtyArtyArtemis** [ElenaiDev/ElenaiDodge2.0#4]
The Tough As Nails mod by Glitchfiend (https://www.curseforge.com/minecraft/mc-mods/tough-as-nails) has recently been ported to 1.16 and includes a survival "thirst" mechanic, requiring you to drink water in a similar fashion to eating. Currently, it basically only affects you in the same way your Hunger bar would (limits sprinting, can cause damage/death, etc.).

My suggestion is simple: When Tough As Nails is installed, have the player's Thirst bar dictate the regeneration of ElenaiDodge's stamina/Feather bar, almost exactly in the same manner that the vanilla Hunger bar dictates the regeneration of Health.

This would not only add an interesting survival element to ElenaiDodge, it would make Tough As Nails's Thirst feature less of a pointlessly difficult addition and actually give it a place in the game's progression. It would separate Hunger and Thirst into two separate mechanics that affect the player differently.

Tough As Nails for 1.16 is currently closed source, but the mod page says "We will also be providing other modders with access to the source on a case-by-case basis.  Please ask Adubbz about it in our Discord server."

**Comment by ElenaiDev** [comment]
Now this is an excellent suggestion.

I'll be in contact with the developer to see if I can integrate this feature.
Thank you for such an in-depth suggestion, I'll see what I can do.

Of course, I can't promise anything as I have yet to be given access to the source code and don't know how it operates, but I will keep you updated.

**Comment by ElenaiDev** [comment]
Closed as this is included in version 2.0.2 of the mod. Enjoy!
