### ISSUE TITLE
Crash upon loading game

### ISSUE THREAD

**Issue by gglobensky** [ElenaiDev/ElenaiDodge2.0#70]
Hi, I added this mod to my modpack on 1.18.2 forge 40.1.80 and the game crashed when loading the world with this cause:
NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_108629_()" because "this.f_104565_.f_91074_" is null

I removed Feathers and Elenai's Dodge and my game would load up again.

Thanks a whole lot for the nice mods!

Full crashlog:
https://pastebin.com/YercjceD

**Comment by ElenaiDev** [comment]
Hi! Thanks for raising the issue. Would you be so kind as to share your mod list as well?

Also, did you install the latest version of playerAnimator? (I foolishly didn’t list it as required when I first uploaded the 1.18 version of mod).

Thank you very much for your kind words!

**Comment by gglobensky** [comment]
I did not have the latest version of playerAnimator.
I will retry with it and get back to you. 
If it still doesn't work I'll share with you my modlist.
I apologize I thought it was in the report.

**Comment by gglobensky** [comment]
I confirm updating the library resolved the issue.

Thanks for your help!

**Comment by ElenaiDev** [comment]
Thanks for the feedback! Entirely my fault for not making the requirement clearer, enjoy the mod! :)
