### ISSUE TITLE
[Suggestion] Make Dodge Sound configurable

### ISSUE THREAD

**Issue by u-ares** [ElenaiDev/ElenaiDodge2.0#73]
Hello! I am currently making a modpack right now using this mod, and it works surprisingly well! Except for the sounds...
You see, in my modpack, I replaced a ton of minecraft's default hit sounds, sweep sounds and all.
You can already guess what happened, dodging making a random meaty hit noise instead of what it should be.

I'm just here to suggest that you add the ability to change the dodge sound to a custom sound. Either by digging into the mod, using a resource pack or maybe a config option?

Thanks!

**Comment by ElenaiDev** [comment]
Will release this very soon! Thanks for the suggestion :)
It will have its own copy of the sweep sound, and you can change it to your liking with resource packs.
