### ISSUE TITLE
Rolling animation on 1.16.5 

### ISSUE THREAD

**Issue by Nikowsky132** [ElenaiDev/ElenaiDodge2.0#75]
I was wondering if the rolling animation is available on 1.16.5 because whenever I dodge there's no animation and I don't know if it is available for 1.19 only or something like that.

**Comment by ElenaiDev** [comment]
It's only available on 1.18 and 19 at the moment I'm afraid. I might look into adding it to 1.16 in the future, but for now I don't have the time to work on older versions. Sorry for the bad news!
