### ISSUE TITLE
[Suggestion] Construct's Armory compatibility

### ISSUE THREAD

**Issue by Sereath** [ElenaiDev/ElenaiDodge2.0#8]
The weight mechanic is actually an awesome thing however it does not recognize any of the Construct's Armory parts while it still does penalize every other kind of armor within the same modpack.

Ender IO's endgames armor with 30 armor points = 100% Steel feathers
![image](https://user-images.githubusercontent.com/54506307/108111263-15338e80-705a-11eb-9050-9c5b0d7dcb01.png)

Construct's Armory set with close to 50 armor points = All the feathers are available
![image](https://user-images.githubusercontent.com/54506307/108111651-99861180-705a-11eb-83ff-018ee65bdf1f.png)

I'm not sure if you could even add compatibility with Construct's Armory since every armor piece there is modular. Perhaps by just adding weight to the player depending on how many armor points the player has at a time? Hopefully you don't have to compromise any of the current mod's functionality for this since its already great.

Thanks for your time!

**Comment by ElenaiDev** [comment]
Hi! Thank you for providing such an in-depth issue, I really appreciate the time that went into it.

I'll aim to patch this soon :)

Thank you!

**Comment by ElenaiDev** [comment]
UPDATE: Sorry I've taken so long to get round to doing this!

I've now learned how the API works and have almost finished the patch, expect an update in the next few days :)

**Comment by ElenaiDev** [comment]
Closing as this was patched in 2.0.3!
