### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by itsdeadfrosty** [ElenaiDev/ElenaiDodge2.0#85]
I know it would be more work, but what do you think about Not only limiting the amount of dodges. But. Also scaling the distance traveled with the dodge Based on armor weight? If I'm wearing very little armor at all, I should be able to dodge pretty far because I don't have to carry as much weight in the air. But if I'm wearing very heavy armor, I might be able to get a dodge or two and but I'm not going to be going nearly as far. I wish it were possible to scale it.

**Comment by HaiSamuel** [comment]
![image](https://github.com/ElenaiDev/ElenaiDodge2.0/assets/122387469/7492a2fa-e4c8-4ba6-893c-d0754508ce14)
