### ISSUE TITLE
[Suggestion] Classic Bar compatibility

### ISSUE THREAD

**Issue by Miner239** [ElenaiDev/ElenaiDodge2.0#9]
The feather bar currently isn't rendered when [Classic Bars](https://www.curseforge.com/minecraft/mc-mods/classic-bars) is enabled. It seems like there is a way to register a new bar into the mod, but I don't know the details.

**Comment by ElenaiDev** [comment]
Thanks for posting this issue!

I'll see what I can do, but the issue may be on Classic Bar's side. It seems to be having issues with many other mods too.

Thanks for your time!

**Comment by ElenaiDev** [comment]
Hey!

So an update on this, I'm currently attempting to add compatibility but it isn't looking likely to be done **soon**. The way Classic Bars is coded means that my GUI only shows up 10% of the time... And I have yet to find a solution!

I'll keep you updated :)

**Comment by ElenaiDev** [comment]
Closing as I have submitted a pull request for Classic Bars that adds compatibility on their end. They just need to accept it and upload the new file.

**Comment by Miner239** [comment]
Hello, I've requested a pull on your branch that should lessen tfarcenim's work to integrate your changes.

**Comment by ElenaiDev** [comment]
Thanks so much! I didn't realize I'd messed up their locations.
