### ISSUE TITLE
[Sugestion] 1.20.1 Update

### ISSUE THREAD

**Issue by luoxiawuchen** [ElenaiDev/ElenaiDodge2.0#90]
May I ask if the author can update your excellent work to the latest 1.20.1? thanks.

**Comment by Talan67** [comment]
Seems like the 1.19.4 Version could work but they would need to fix whatever is causing this crash

[latest.log](https://github.com/ElenaiDev/ElenaiDodge2.0/files/12339144/latest.log)
[crash-2023-08-14_20.51.04-client.txt](https://github.com/ElenaiDev/ElenaiDodge2.0/files/12339145/crash-2023-08-14_20.51.04-client.txt)

**Comment by ElenaiDev** [comment]
Done! Thank you for your kind words :)
